name: delete old workflow runs

on: [push]
schedule:
  # UTC (国内 UTC+8)
  - cron: '15 16 * * *'
 # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        with:
          repository: seav1/ChatGPT-Telegram-Workers   # replace this with your own repository
          older-than-seconds: 86400        # remove all workflow runs older than 7 day
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
