# This is a basic workflow to help you get started with Actions
name: delete-old-workflow-runs
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  schedule:
    # UTC (国内 UTC+8)
    - cron: '15 16 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Delete old workflow runs

    steps:
      - name: Delete old workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        with:
          repository: ${{ github.repository }}
          older-than-seconds: 86400 # remove all workflow runs older than 1 day >> 24*60*60=86400
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
