# File: .github/workflows/repo-sync.yml
name: 自动同步
on:
  schedule:
    - cron: '0 4,16  * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: repo-sync
jobs:
  repo-sync:
    env:
      PAT: ${{ github.event.client_payload.PAT || secrets.PAT }}

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v3
      - uses: repo-sync/github-sync@v2

        with:


      - name: autosync
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/TBXark/ChatGPT-Telegram-Workers.git"
          source_branch: "master"
          destination_branch: "master"
          github_token: ${{ github.event.client_payload.PAT || secrets.PAT }}
